Dev
antoniukivan/jv-create-annotation pull request #1
Opened 2021-01-07 15:55 UTC by antoniukivan

2021-01-07 17:08 UTC, YuraBondarenko approved these changes

2021-01-08 09:34 UTC, KseniiaMakarova requested changes

2021-01-08 09:34 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            } catch (NumberFormatException e) {
what about ArrayIndexOutOfBoundException? let’s catch it here as well

2021-01-08 09:34 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            betDao.add(bet);
let’s save  the bet if it is not null

2021-01-08 09:34 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            System.out.println(bet == null ? null : bet.toString());
```suggestion
            System.out.println(bet);
```

2021-01-08 09:34 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/BetDaoImpl.java
> +
redundant empty line

2021-01-08 09:34 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/dao/UserDaoImpl.java
> +
same

2021-01-08 09:34 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/model/User.java
> +    private int id;
let's not have an id for now
in future all our entities will have an id, not only user
```suggestion
    private int age;
```

2021-01-08 09:34 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/model/User.java
> +    private String login;
```suggestion
    private String name;
```

2021-01-08 14:23 UTC, KseniiaMakarova requested changes

2021-01-08 14:23 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/model/User.java
> +    }
fix variable names

2021-01-08 14:23 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/model/User.java
> +                + '}';
here as well

2021-01-08 14:50 UTC, antoniukivan commented on src/main/java/core/basesyntax/model/User.java
> +                + '}';
my bad)

2021-01-08 14:51 UTC, KseniiaMakarova requested changes

2021-01-08 14:51 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/model/User.java
> +    public User(String name, int id) {
id -> age

2021-01-08 14:51 UTC, KseniiaMakarova commented on src/main/java/core/basesyntax/model/User.java
> +                + ", id = " + age
```suggestion
                + ", age = " + age
```

2021-01-08 15:19 UTC, KseniiaMakarova approved these changes

2021-01-10 19:33 UTC, merged